"""The index, as a projection of the decision files.

Nothing here is authored. Every word comes from a decision's own
frontmatter, which is what makes two copies of a status impossible:
there is one copy, and this is a view of it.
"""

import os
from pathlib import Path

from _docs import Decision

GENERATED = "<!-- generated by paper-trail; edit the decision files, not this -->"

COLUMNS = "| Id | Decision | Status | Conclusion |\n|---|---|---|---|"


def escape(text: str) -> str:
    """A table cell cannot hold a bare pipe.

    Measured on a real table before it was replaced: two rows carried one
    inside a code span and rendered with extra columns for months without
    anyone noticing.
    """
    return text.replace("|", r"\|")


def _row(item: Decision, *, index: Path) -> str:
    link = os.path.relpath(item.path, index.parent)
    return (
        f"| {item.id} | [{escape(item.title)}]({Path(link).as_posix()}) "
        f"| {escape(item.status)} | {escape(item.conclusion)} |"
    )


def _section(heading: str, items: list[Decision], *, empty: str, index: Path) -> list[str]:
    if not items:
        return [heading, "", empty, ""]
    return [heading, "", COLUMNS, *(_row(item, index=index) for item in items), ""]


def render(decisions: list[Decision], *, root: Path, index: Path) -> str:
    """The whole file. Same decisions, same bytes."""
    ordered = sorted(decisions, key=lambda item: item.id)
    live = [item for item in ordered if item.status == "open"]
    settled = [item for item in ordered if item.status != "open"]

    lines = [
        GENERATED,
        "",
        "# Decisions",
        "",
        "One file per decision under the directory this repo's",
        "`.paper-trail.toml` names. This page is written from them.",
        "",
        *_section("## Open", live, empty="Nothing open.", index=index),
        *_section("## Settled", settled, empty="Nothing settled yet.", index=index),
    ]
    return "\n".join(lines).rstrip("\n") + "\n"
