"""The index, as a projection of the decision files.

Nothing here is authored. Every word comes from a decision's own
frontmatter, which is what makes two copies of a status impossible:
there is one copy, and this is a view of it. See docs/decisions/0004.
"""

import os
from pathlib import Path

from _docs import PLACEHOLDER, Debt, Decision, Investigation

GENERATED = "<!-- generated by paper-trail; edit the decision files, not this -->"

COLUMNS = "| Id | Decision | Status | Conclusion |\n|---|---|---|---|"


def escape(text: str) -> str:
    """A table cell cannot hold a bare pipe.

    Measured on a real table before it was replaced: two rows carried one
    inside a code span and rendered with extra columns for months without
    anyone noticing.
    """
    return text.replace("|", r"\|")


def _status(item: Decision, replaces: list[str]) -> str:
    """The status, with the supersede trail read in both directions.

    Only the older decision says it was replaced. The newer one's
    "replaces" is derived here rather than written in its file, so there
    is one copy of the fact and it cannot disagree with itself.
    """
    text = item.status
    if item.superseded_by:
        text += f" by {item.superseded_by}"
    if replaces:
        text += f", replaces {', '.join(replaces)}"
    return escape(text)


def _row(item: Decision, *, index: Path, replaces: list[str]) -> str:
    link = os.path.relpath(item.path, index.parent)
    return (
        f"| {item.id} | [{escape(item.title)}]({Path(link).as_posix()}) "
        f"| {_status(item, replaces)} | {escape(item.conclusion)} |"
    )


def _section(
    heading: str,
    items: list[Decision],
    *,
    empty: str,
    index: Path,
    replaced: dict[str, list[str]],
) -> list[str]:
    if not items:
        return [heading, "", empty, ""]
    rows = (_row(item, index=index, replaces=replaced.get(item.id, [])) for item in items)
    return [heading, "", COLUMNS, *rows, ""]


def render(decisions: list[Decision], *, root: Path, index: Path) -> str:
    """The whole file. Same decisions, same bytes."""
    ordered = sorted(decisions, key=lambda item: item.id)
    live = [item for item in ordered if item.status == "open"]
    settled = [item for item in ordered if item.status != "open"]
    replaced: dict[str, list[str]] = {}
    for item in ordered:
        if item.superseded_by:
            replaced.setdefault(str(item.superseded_by), []).append(item.id)

    lines = [
        GENERATED,
        "",
        "# Decisions",
        "",
        "One file per decision under the directory this repo's",
        "`.paper-trail.toml` names. This page is written from them.",
        "",
        *_section("## Open", live, empty="Nothing open.", index=index, replaced=replaced),
        *_section("## Settled", settled, empty="Nothing settled yet.", index=index, replaced=replaced),
    ]
    return "\n".join(lines).rstrip("\n") + "\n"


INVESTIGATIONS_GENERATED = GENERATED.replace("the decision files", "the investigation files")

OPEN_COLUMNS = "| Id | Investigation | Opened | Next |\n|---|---|---|---|"

ANSWERED_COLUMNS = "| Id | Investigation | Answered | Decision |\n|---|---|---|---|"


def next_step(body: str) -> str:
    """The first line under `## Next`, which is where the hunt stands.

    Blank while it is still the template's placeholder.

    Empty when there is no such section: a working file is allowed to be
    shaped differently, and an index that refused it would be in the way.
    """
    lines = iter(body.split("\n"))
    for line in lines:
        if line.strip() == "## Next":
            for after in lines:
                if after.startswith("## "):
                    return ""
                if after.strip():
                    return "" if after.strip().startswith(PLACEHOLDER) else after.strip()
    return ""


def _link(item: Investigation | Debt, *, index: Path) -> str:
    link = Path(os.path.relpath(item.path, index.parent)).as_posix()
    return f"[{escape(item.title)}]({link})"


def render_investigations(
    investigations: list[Investigation], decisions: list[Decision], *, index: Path
) -> str:
    """The investigations index, a projection like the decision one.

    Dated by when each was opened and never by how long it has sat: an
    age would change every day without a file changing, and the
    is-it-current check would fail on a clean record.
    """
    ordered = sorted(investigations, key=lambda item: item.id)
    live = [item for item in ordered if item.answered is None]
    done = [item for item in ordered if item.answered is not None]
    kept = {item.id: item for item in decisions}

    def decided(item: Investigation) -> str:
        found = kept.get(item.decision or "")
        if found is None:
            return escape(item.decision or "")
        link = Path(os.path.relpath(found.path, index.parent)).as_posix()
        return f"[{found.id}]({link})"

    lines = [
        INVESTIGATIONS_GENERATED,
        "",
        "# Investigations",
        "",
        "What is being hunted, and what has been answered. This page is",
        "written from the investigation files.",
        "",
        "## Open",
        "",
    ]
    if live:
        lines += [OPEN_COLUMNS]
        lines += [
            f"| {item.id} | {_link(item, index=index)} | {item.opened} "
            f"| {escape(next_step(item.body))} |"
            for item in live
        ]
    else:
        lines += ["Nothing open."]
    lines += ["", "## Answered", ""]
    if done:
        lines += [ANSWERED_COLUMNS]
        lines += [
            f"| {item.id} | {_link(item, index=index)} | {item.answered} | {decided(item)} |"
            for item in done
        ]
    else:
        lines += ["Nothing answered yet."]
    return "\n".join(lines) + "\n"


DEBT_OPEN_COLUMNS = "| Id | Debt | Opened | Repay when |\n|---|---|---|---|"

DEBT_RESOLVED_COLUMNS = "| Id | Debt | Resolved | Decision |\n|---|---|---|---|"


def render_debt(items: list[Debt], decisions: list[Decision], *, index: Path) -> str:
    """The debt index: what is owed, and the condition that makes it worth paying.

    States the open count, because "how many are there" is the first
    thing asked of it and counting table rows is how that goes wrong.
    """
    ordered = sorted(items, key=lambda item: item.id)
    live = [item for item in ordered if item.resolved is None]
    done = [item for item in ordered if item.resolved is not None]
    kept = {item.id: item for item in decisions}

    def decided(item: Debt) -> str:
        found = kept.get(item.decision or "")
        if found is None:
            return escape(item.decision or "")
        link = Path(os.path.relpath(found.path, index.parent)).as_posix()
        return f"[{found.id}]({link})"

    lines = [
        GENERATED.replace("the decision files", "the debt files"),
        "",
        "# Debt",
        "",
        "Shortcuts taken on purpose, each with the condition that makes it",
        "worth paying back. This page is written from the debt files.",
        "",
        "## Open",
        "",
    ]
    if live:
        lines += [f"{len(live)} open.", "", DEBT_OPEN_COLUMNS]
        lines += [
            f"| {item.id} | {_link(item, index=index)} | {item.opened} "
            f"| {escape(item.repay_when)} |"
            for item in live
        ]
    else:
        lines += ["Nothing open."]
    lines += ["", "## Resolved", ""]
    if done:
        lines += [DEBT_RESOLVED_COLUMNS]
        lines += [
            f"| {item.id} | {_link(item, index=index)} | {item.resolved} | {decided(item)} |"
            for item in done
        ]
    else:
        lines += ["Nothing resolved yet."]
    return "\n".join(lines) + "\n"
